<!DOCTYPE html>
<html>
<head>
    <title>New Sails App</title>

    <!-- Viewport mobile tag for sensible mobile support -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <!--
        Stylesheets and Preprocessors
        ==============================

        You can always bring in CSS files manually with `<link>` tags, or asynchronously
        using a solution like AMD (RequireJS).  Or, if you like, you can take advantage
        of Sails' conventional asset pipeline (boilerplate Gruntfile).

        By default, stylesheets from your `assets/styles` folder are included
        here automatically (between STYLES and STYLES END). Both CSS (.css) and LESS (.less)
        are supported. In production, your styles will be minified and concatenated into
        a single file.

        To customize any part of the built-in behavior, just edit `tasks/pipeline.js`.
        For example, here are a few things you could do:

            + Change the order of your CSS files
            + Import stylesheets from other directories
            + Use a different or additional preprocessor, like SASS, SCSS or Stylus
    -->


    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/ionicons.min.css">
    <link rel="stylesheet" href="/css/morris/morris.css">
    <link rel="stylesheet" href="/css/jvectormap/jquery-jvectormap-1.2.2.css">
    <link rel="stylesheet" href="/css/datepicker/datepicker3.css">
    <link rel="stylesheet" href="/css/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="/css/iCheck/all.css">
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/css/style.css">

</head>

<body class="skin-black">


<?php echo $this->partial('backend/partials/admin-header.phtml', array()); ?>

<div class="wrapper row-offcanvas row-offcanvas-left">
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="left-side sidebar-offcanvas">
        <?php echo $this->partial('backend/partials/admin-sidebar.phtml', array()); ?>
    </aside>

    <aside class="right-side">

        <?php echo $this->content; ?>

        <div class="footer-main">
            Copyright &copy Gülenayva | Witvox, 2015
        </div>
    </aside><!-- /.right-side -->

</div><!-- ./wrapper -->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<script src="/js/dependencies/sails.io.js"></script>
<!--<script src="/js/jquery.min.js" type="text/javascript"></script>-->

<!-- Bootstrap -->
<script src="/js/bootstrap.min.js" type="text/javascript"></script>
<!-- jQuery UI 1.10.3 -->
<script src="/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
<!-- daterangepicker -->
<script src="/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>

<script src="/js/plugins/chart.js" type="text/javascript"></script>

<!-- datepicker
<script src="js/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>-->
<!-- Bootstrap WYSIHTML5
<script src="js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>-->
<!-- iCheck -->
<script src="/js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
<!-- calendar -->
<script src="/js/plugins/fullcalendar/fullcalendar.js" type="text/javascript"></script>

<!-- Director App -->
<script src="/js/Director/app.js" type="text/javascript"></script>

<!-- Director dashboard demo (This is only for demo purposes) -->
<script src="/js/Director/dashboard.js" type="text/javascript"></script>
<script src="/js/custom.js" type="text/javascript"></script>

<!-- Gülenayva angularjs -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/TweenMax.min.js"></script>
<!--<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/CSSRulePlugin.min.js"></script>-->
<!--<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/RaphaelPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/ColorPropsPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/EaselPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/TextPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/ScrollToPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/KineticPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/utils/Draggable.min.js"></script>-->

<!--<script src="//code.jquery.com/ui/1.10.4/jquery-ui.min.js"></script>-->
<script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
<script src="/js/vendor/angular.min.js"></script>
<script src="/js/vendor/angular-resource.min.js"></script>
<script src="/js/vendor/angular-sanitize.min.js"></script>
<script src="/js/vendor/angular-route.min.js"></script>
<script src="/js/vendor/angular-animate.min.js"></script>

<script data-main="/js/gaboot-admin" src="/js/vendor/require.2.1.9.js"></script>
<!-- Gülenayva angularjs end -->
</body>
</html>
