<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>YazarPatent</title>

    <!-- Viewport mobile tag for sensible mobile support -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <!--
        Stylesheets and Preprocessors
        ==============================

        You can always bring in CSS files manually with `<link>` tags, or asynchronously
        using a solution like AMD (RequireJS).  Or, if you like, you can take advantage
        of Sails' conventional asset pipeline (boilerplate Gruntfile).

        By default, stylesheets from your `assets/styles` folder are included
        here automatically (between STYLES and STYLES END). Both CSS (.css) and LESS (.less)
        are supported. In production, your styles will be minified and concatenated into
        a single file.

        To customize any part of the built-in behavior, just edit `tasks/pipeline.js`.
        For example, here are a few things you could do:

            + Change the order of your CSS files
            + Import stylesheets from other directories
            + Use a different or additional preprocessor, like SASS, SCSS or Stylus
    -->


    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/yazarpatent.css">

</head>

<body>

<div class="container main-content">
    <div class="col-md-3 left-sidebar">
        <?php echo $this->partial('backend/partials/admin-sidebar.phtml', array()); ?>
    </div>
    <div class="col-md-9 streaming">
        <div class="col-md-12 streaming-header">
            <?php echo $this->partial('backend/partials/admin-header.phtml', array()); ?>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-12 streaming-content">
            <?php echo $this->content; ?>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-12 footer">
            <?php echo $this->partial('backend/partials/admin-footer.phtml', array()); ?>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<script src="/js/dependencies/sails.io.js"></script>
<!--<script src="/js/jquery.min.js" type="text/javascript"></script>-->

<!-- Bootstrap -->
<script src="/js/bootstrap.min.js" type="text/javascript"></script>
<!-- jQuery UI 1.10.3 -->
<script src="/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>

<script src="/js/plugins/chart.js" type="text/javascript"></script>

<!-- Gülenayva angularjs -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/TweenMax.min.js"></script>
<!--<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/CSSRulePlugin.min.js"></script>-->
<!--<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/RaphaelPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/ColorPropsPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/EaselPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/TextPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/ScrollToPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/plugins/KineticPlugin.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.11.2/utils/Draggable.min.js"></script>-->

<!--<script src="//code.jquery.com/ui/1.10.4/jquery-ui.min.js"></script>-->
<script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
<script src="/js/vendor/angular.min.js"></script>
<script src="/js/vendor/angular-resource.min.js"></script>
<script src="/js/vendor/angular-sanitize.min.js"></script>
<script src="/js/vendor/angular-route.min.js"></script>
<script src="/js/vendor/angular-animate.min.js"></script>

<script data-main="/js/gaboot-admin" src="/js/vendor/require.2.1.9.js"></script>
<!-- Gülenayva angularjs end -->
</body>
</html>
