<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
        <div class="pull-left image">
            <img src="/images/26115.jpg" class="img-circle" alt="User Image" />
        </div>
        <div class="pull-left info">
            <p>Gülen Ayva</p>

            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
    </div>
    <!-- search form -->
    <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Ara..."/>
                                    <span class="input-group-btn">
                                        <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                                    </span>
        </div>
    </form>
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
        <li class="active">
            <a href="/backend/dashboard">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            </a>
        </li>
        <li>
            <a href="/backend/headlines">
                <i class="fa fa-list-ul"></i> <span>Başlıklar</span>
            </a>
        </li>

        <li>
            <a href="/backend/posts">
                <i class="fa fa-microphone"></i> <span>Gönderiler</span>
            </a>
        </li>

        <li>
            <a href="/backend/users">
                <i class="fa fa-users"></i> <span>Kullanıcılar</span>
            </a>
        </li>

        <li>
            <a href="/backend/replies">
                <i class="fa fa-comments"></i> <span>Yorumlar</span>
            </a>
        </li>

    </ul>
</section>
<!-- /.sidebar -->
